server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

lostlink:
  storage:
    type: gcs
    local-dir: ./uploads
    local-url-prefix: http://10.160.0.2:8083/uploads/
    bucket-name: lostlink-cloud-platform-2020

eureka:
  client:
    service-url:
      defaultZone: http://10.160.0.2:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
