server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://34.21.191.131:5432/findora_users?sslmode=require
    username: postgres
    password: Charuka@974
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://10.160.0.4:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info