server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://136.85.68.131:5432/lostlink_users?sslmode=require
    username: root
    password: Lostlink@2020
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://10.160.0.3:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info